class Urls:
    URL_MAIN_PAGE = 'https://stellarburgers.nomoreparties.site'
    URL_LOGIN_PAGE = '/login'
    URL_FORGOT_PASSWORD = '/forgot-password'
    URL_RESET_PASSWORD_PAGE = '/reset-password'
    URL_ACCOUNT_PROFILE = '/account/profile'
    URL_ORDER_HISTORY = '/account/order-history'
    URL_ORDER_LIST_PAGE = '/feed'
    URL_CREATE_USER = '/api/auth/register'
    URL_LOGIN_USER = '/api/auth/login'
    URL_DELETE_USER = '/api/auth/user'
